import Head from "next/head";
// import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import ColorSection from "../components/Layout/ColorSection";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header />
      <body>
        <section id="hero"></section>
        <section>
          <ColorSection color="#2b2b"></ColorSection>
        </section>
      </body>
    </div>
  );
}
