import Head from "next/head";
import Header from "../components/Header/Header";
import ColorSection from "../components/Layout/ColorSection";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header />

      <section id="hero" className="h-[90vh]"></section>
      <section>
        <ColorSection color="#2b2b">
          <p>Ciao</p>
        </ColorSection>
      </section>
    </div>
  );
}
